### ISSUE TITLE
Drag&Drop varios ficheros

### ISSUE THREAD

**Issue by danielquijada** [MauricioMCavalleriS/Analizador_Lexico_JS#4]
Al arrastrar varios ficheros es mejor coger sólo uno, o que los coja todos y los concatene?

**Comment by MauricioMCavalleriS** [comment]
Yo creo que es mejor que solo coja uno porque si arrastras otro lo que normalmente preferirías es que te lo cargara desde 0, en tal caso tendríamos que implementar un limpiar o que te diera una u otra opción pero eso no creo que ni haga falta y simplemente que quede como que si arrastras otro se cargara ese otro.

**Comment by danielquijada** [comment]
Sisi, eso está claro, lo que me refiero es, si arrastras varios A LA VEZ, tipo coges 3 o así y los arrastras: en ese caso, qué hacer?

**Comment by MauricioMCavalleriS** [comment]
AHHHH! pueees dudo que sea realmente importante implementar esa situación pero si la implementáramos yo creo que podríamos hacer o que se concatenaran ooooo! quizás se podría hacer para que se abra en plan target blank y se carguen las dos por separado? Yo creo que como mucho mejor si lo ponemos concatenado y ya esta si no es mucho problema o sino directamente no contemplar esa situación y que se cargue el primero y ya esta o que de error.

**Comment by danielquijada** [comment]
Modificado, ahora cuando colocas elementos, sean cuantos sean, se elimina el contenido actual, y luego se colocan uno seguido del otro (separados por un salto de línea, quizás lo cambie por una línea en blanco).
