### ISSUE TITLE
Pruebas!!

### ISSUE THREAD

**Issue by danielquijada** [MauricioMCavalleriS/Analizador_Lexico_JS#6]
Faltan las pruebas, hay que ver qué pruebas hacemos (poniendole aunque sea cosas simples en la entrada para tener la salida).

Además, añadir Travis

**Comment by MauricioMCavalleriS** [comment]
Ya corregí las pruebas :3 (era una chorrada por cierto xD)

**Comment by danielquijada** [comment]
Añadidas pruebas para cubrir el resto del código.
